"""onboarding + mailbox_connections

Revision ID: 120b8ef2c964
Revises: 58211d822529
Create Date: 2026-07-12 19:02:54.989301
"""
from alembic import op
import sqlalchemy as sa


revision = '120b8ef2c964'
down_revision = '58211d822529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('app_password_enc', sa.Text(), nullable=True),
    sa.Column('imap_host', sa.String(length=120), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('smtp_host', sa.String(length=120), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_connections_workspace_id'), 'mailbox_connections', ['workspace_id'], unique=False)
    op.create_table('onboardings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboardings_token'), 'onboardings', ['token'], unique=True)
    op.create_index(op.f('ix_onboardings_workspace_id'), 'onboardings', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboardings_workspace_id'), table_name='onboardings')
    op.drop_index(op.f('ix_onboardings_token'), table_name='onboardings')
    op.drop_table('onboardings')
    op.drop_index(op.f('ix_mailbox_connections_workspace_id'), table_name='mailbox_connections')
    op.drop_table('mailbox_connections')
    # ### end Alembic commands ###
