"""reply_leads legacy_id

Revision ID: 2acec5684300
Revises: fa09293e9327
Create Date: 2026-07-12 16:32:28.086205
"""
from alembic import op
import sqlalchemy as sa


revision = '2acec5684300'
down_revision = 'fa09293e9327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply_leads', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reply_leads_legacy_id'), 'reply_leads', ['legacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_leads_legacy_id'), table_name='reply_leads')
    op.drop_column('reply_leads', 'legacy_id')
    # ### end Alembic commands ###
