"""reply management module + enrich esp

Revision ID: 431cf04dcf0c
Revises: cf4d5f487f62
Create Date: 2026-07-12 10:30:00.075185
"""
from alembic import op
import sqlalchemy as sa


revision = '431cf04dcf0c'
down_revision = 'cf4d5f487f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('reply_workspace', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('dedupe_key', sa.String(length=512), nullable=True),
    sa.Column('external_lead_id', sa.String(length=255), nullable=True),
    sa.Column('reply_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('campaign', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('intent', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=True),
    sa.Column('conf_num', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('reply_added', sa.Boolean(), nullable=True),
    sa.Column('fup_added', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('main_reply', sa.Text(), nullable=True),
    sa.Column('followups', sa.JSON(), nullable=True),
    sa.Column('thread', sa.JSON(), nullable=True),
    sa.Column('lead_data', sa.JSON(), nullable=True),
    sa.Column('send_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_leads_dedupe_key'), 'reply_leads', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_reply_leads_reply_workspace'), 'reply_leads', ['reply_workspace'], unique=False)
    op.create_index(op.f('ix_reply_leads_workspace_id'), 'reply_leads', ['workspace_id'], unique=False)
    op.create_table('reply_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('reply_followup_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('sender_name', sa.Text(), nullable=True),
    sa.Column('default_sender_email', sa.Text(), nullable=True),
    sa.Column('calendly_token_enc', sa.Text(), nullable=True),
    sa.Column('calendly_scheduling_url', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=20), nullable=True),
    sa.Column('ai_fallback', sa.Boolean(), nullable=True),
    sa.Column('openai_key_enc', sa.Text(), nullable=True),
    sa.Column('gemini_key_enc', sa.Text(), nullable=True),
    sa.Column('client_profile', sa.JSON(), nullable=True),
    sa.Column('reply_format', sa.JSON(), nullable=True),
    sa.Column('ai_rules', sa.Text(), nullable=True),
    sa.Column('reply_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_reply_workspaces_workspace_id'), 'reply_workspaces', ['workspace_id'], unique=False)
    op.add_column('enrich_leads', sa.Column('esp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrich_leads', 'esp')
    op.drop_index(op.f('ix_reply_workspaces_workspace_id'), table_name='reply_workspaces')
    op.drop_table('reply_workspaces')
    op.drop_index(op.f('ix_reply_leads_workspace_id'), table_name='reply_leads')
    op.drop_index(op.f('ix_reply_leads_reply_workspace'), table_name='reply_leads')
    op.drop_index(op.f('ix_reply_leads_dedupe_key'), table_name='reply_leads')
    op.drop_table('reply_leads')
    # ### end Alembic commands ###
