"""proposed_slots

Revision ID: 58211d822529
Revises: 2acec5684300
Create Date: 2026-07-12 17:49:24.796155
"""
from alembic import op
import sqlalchemy as sa


revision = '58211d822529'
down_revision = '2acec5684300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('reply_workspace', sa.String(length=255), nullable=True),
    sa.Column('prospect', sa.String(length=255), nullable=True),
    sa.Column('slot_utc', sa.String(length=40), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_slots_reply_workspace'), 'proposed_slots', ['reply_workspace'], unique=False)
    op.create_index(op.f('ix_proposed_slots_slot_utc'), 'proposed_slots', ['slot_utc'], unique=False)
    op.create_index(op.f('ix_proposed_slots_workspace_id'), 'proposed_slots', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposed_slots_workspace_id'), table_name='proposed_slots')
    op.drop_index(op.f('ix_proposed_slots_slot_utc'), table_name='proposed_slots')
    op.drop_index(op.f('ix_proposed_slots_reply_workspace'), table_name='proposed_slots')
    op.drop_table('proposed_slots')
    # ### end Alembic commands ###
