"""job progress tracking

Revision ID: 7df433f3bf3c
Revises: fa785bd597ff
Create Date: 2026-07-11 11:43:15.149948
"""
from alembic import op
import sqlalchemy as sa


revision = '7df433f3bf3c'
down_revision = 'fa785bd597ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('progress_note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'progress_note')
    op.drop_column('jobs', 'progress')
    # ### end Alembic commands ###
