"""worker heartbeats

Revision ID: 929417ea2ebf
Revises: 7df433f3bf3c
Create Date: 2026-07-11 16:50:19.601664
"""
from alembic import op
import sqlalchemy as sa


revision = '929417ea2ebf'
down_revision = '7df433f3bf3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
