"""enrichment lists module

Revision ID: a8d60b60254c
Revises: 929417ea2ebf
Create Date: 2026-07-12 09:42:27.216351
"""
from alembic import op
import sqlalchemy as sa


revision = 'a8d60b60254c'
down_revision = '929417ea2ebf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrich_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('icp_definition', sa.Text(), nullable=True),
    sa.Column('formats', sa.JSON(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('skip_title_gate', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('enrich_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrich_lists_workspace_id'), 'enrich_lists', ['workspace_id'], unique=False)
    op.create_table('enrich_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('free_status', sa.String(length=40), nullable=True),
    sa.Column('email_status', sa.String(length=40), nullable=True),
    sa.Column('verify_source', sa.String(length=20), nullable=True),
    sa.Column('title_status', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('icp_decision', sa.String(length=40), nullable=True),
    sa.Column('icp_score', sa.Integer(), nullable=True),
    sa.Column('icp_reason', sa.Text(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['enrich_lists.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrich_leads_email'), 'enrich_leads', ['email'], unique=False)
    op.create_index(op.f('ix_enrich_leads_icp_decision'), 'enrich_leads', ['icp_decision'], unique=False)
    op.create_index(op.f('ix_enrich_leads_list_id'), 'enrich_leads', ['list_id'], unique=False)
    op.create_index(op.f('ix_enrich_leads_status'), 'enrich_leads', ['status'], unique=False)
    op.create_index(op.f('ix_enrich_leads_workspace_id'), 'enrich_leads', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrich_leads_workspace_id'), table_name='enrich_leads')
    op.drop_index(op.f('ix_enrich_leads_status'), table_name='enrich_leads')
    op.drop_index(op.f('ix_enrich_leads_list_id'), table_name='enrich_leads')
    op.drop_index(op.f('ix_enrich_leads_icp_decision'), table_name='enrich_leads')
    op.drop_index(op.f('ix_enrich_leads_email'), table_name='enrich_leads')
    op.drop_table('enrich_leads')
    op.drop_index(op.f('ix_enrich_lists_workspace_id'), table_name='enrich_lists')
    op.drop_table('enrich_lists')
    op.drop_table('enrich_configs')
    # ### end Alembic commands ###
