"""only_safe on enrich_configs

Revision ID: cf4d5f487f62
Revises: a8d60b60254c
Create Date: 2026-07-12 10:10:46.582036
"""
from alembic import op
import sqlalchemy as sa


revision = 'cf4d5f487f62'
down_revision = 'a8d60b60254c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrich_configs', sa.Column('only_safe', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrich_configs', 'only_safe')
    # ### end Alembic commands ###
