"""workspace aliases

Revision ID: fa785bd597ff
Revises: 99d538287e82
Create Date: 2026-07-11 10:10:43.229364
"""
from alembic import op
import sqlalchemy as sa


revision = 'fa785bd597ff'
down_revision = '99d538287e82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_name', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'external_name', name='uq_alias_source_name')
    )
    op.create_index(op.f('ix_workspace_aliases_workspace_id'), 'workspace_aliases', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_aliases_workspace_id'), table_name='workspace_aliases')
    op.drop_table('workspace_aliases')
    # ### end Alembic commands ###
